# Generated by Django 4.2.1 on 2023-06-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_country_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='прошел верификацию'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_kod',
            field=models.IntegerField(blank=True, null=True, verbose_name='код подтверждения'),
        ),
    ]
