# Generated by Django 4.2.1 on 2023-06-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_is_verify_user_verification_kod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_kod',
        ),
    ]
