# Generated by Django 4.2.1 on 2023-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='URL'),
        ),
    ]
