# Generated by Django 4.2.1 on 2023-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('created_data', models.DateTimeField(verbose_name='Дата создания')),
                ('last_changed_data', models.DateTimeField(verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
