# Generated by Django 4.2.1 on 2023-06-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер версии'),
        ),
    ]
